apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: vpn
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: lscr.io/linuxserver/wireguard:latest
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
            sysctls:
            - name: net.ipv4.ip_forward
              value: "1"
          ports:
          - containerPort: 51820
            protocol: UDP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          - name: SERVERURL
            value: "vpn.wieru.com"          
          - name: SERVERPORT
            value: "51820"
          - name: PEERS
            value: "3"
          - name: PEERDNS
            value: "8.8.8.8"
          - name: INTERNAL_SUBNET
            value: "10.13.13.0"
          - name: ALLOWEDIPS
            value: "0.0.0.0/0, ::0/0"            
          - name: LOG_CONFS
            value: "true"

