apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: vpn
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: lscr.io/linuxserver/wireguard:latest
          securityContext:
            allowPrivilegeEscalation: true
          ports:
          - containerPort: 51820
            protocol: UDP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
