apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: vpn
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: alekslitvinenk/openvpn
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_ADMIN
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 1194
            protocol: UDP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: HOST_ADDR
            value: "vpn.wieru.com"
          - name: HOST_TUN_PORT
            value: "1194"
          - name: HOST_CONF_PORT
            value: "80"