apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpn-ingress
  namespace: vpn
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public
  tls:
  - hosts:
    - vpn.wieru.com
    secretName: tls-secret
  rules:
  - host: vpn.wieru.com
    http: 
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: vpn-svc
              port:
                number: 80