apiVersion: v1
kind: Service
metadata:
  name: vpn-svc
  namespace: vpn
spec:
  selector:
    app: app
  ports:
  - name: wireguard-port
    protocol: UDP
    port: 51820
    targetPort: 51820
  externalIPs:
    - 192.168.0.7