apiVersion: v1
kind: Service
metadata:
  name: vpn-svc
  namespace: vpn
spec:
  selector:
    app: app
  ports:
  - name: host-conf-port
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: host-tun-port
    protocol: UDP
    port: 1194
    targetPort: 1194
  # type: NodePort